version: '3'
services:
  ms:
    build:
      context: ./attak
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    tty: true
    networks:
      - default

  target:
    image: pgarneau/defense
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/24