version: '3'
services:
  ms:
    build:
      context: ./attak
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    tty: true
    networks:
      - default

  samba:
    image: vulhub/samba:4.6.3
    networks:
      - default
    volumes:
    - ./samba/smb.conf:/usr/local/samba/etc/smb.conf
    tty: yes
    restart: always

  target:
    image: pgarneau/app3
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/24